### ISSUE TITLE
Implement 'Build Logs' for each build which can be viewed via the file system and UI

### ISSUE THREAD

**Issue by yortus** [paypac/node-concierge#15]
I tried adding a new variant (there still a concierge running here - titangw). It picked up the new git tag, but eventually gave a build status of 'failed'. However I can't see any way to get more information about the cause of the failure. The event log (button on lower left) doesn't seem to show anything of relevance.

Where would I find more info about the failure? Do I need to SSH into the machine running the concierge?

**Comment by Seikho** [comment]
At the moment, yes. You'd need to view the `stdout` of the Concierge.
I'll add a concept of "build logs" so these can more easily be viewed.

**Comment by Seikho** [comment]
Added in commit 2636f14f1
