### ISSUE TITLE
Can install under vagrant, but failing at startup

### ISSUE THREAD

**Issue by yortus** [paypac/node-concierge#16]
Setup:
* windows 10
* vagrant v1.8.6
* VirtualBox v5.1.6
* git bash (MINGW64)

Repro steps (all in git bash, running as administrator):

1. `git clone` the concierge repo into a clean directory
2. `cd` into the cloned concierge directory
3. `vagrant up`
4. `vagrant ssh`
5. `ls` (under `~` shows a single subdirectory `concierge`, i.e. `/home/vagrant/concierge`)
6. `cd /home/vagrant/concierge`
7. `npm install --production`
8. `node .`

```
Error: Cannot find module '/home/vagrant/concierge'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by Seikho** [comment]
Alrighty, this should be resolved with the latest `master`. Pull the latest master and run `npm install` and all should be well.

**Comment by yortus** [comment]
Working! Thanks!!
